"""Fetch the DAIGT (LLM - Detect AI Generated Text) dataset from Kaggle.

The official Kaggle competition "llm-detect-ai-generated-text" ships a
training set that is almost entirely human essays (the Persuade corpus)
plus a small set of GPT-generated essays, with no per-source labels for
the many LLMs used in the hidden test set. That's unusable for this
project, which needs real, labeled generation-source diversity to hold
sources out and simulate "a new AI model appears later" (see CLAUDE.md).

Instead we use thedrcat/daigt-v2-train-dataset, the community-compiled
DAIGT dataset that aggregates the competition's human essays with AI
essays generated by a wide range of models (GPT variants, Llama2, Mistral,
Falcon, etc.), each row labeled with its generation source. This is the
dataset commonly referred to as "the DAIGT dataset" in public writeups of
this competition.

Usage:
    python data/download.py

Requires a Kaggle account and API credentials. If credentials are not
found, this script prints setup instructions and exits non-zero instead
of failing silently.
"""

from __future__ import annotations

import os
import subprocess
import sys
import zipfile
from pathlib import Path

DATASET_SLUG = "thedrcat/daigt-v2-train-dataset"
RAW_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"


def _has_kaggle_credentials() -> bool:
    # Newer kaggle CLI (2.x): token via env var or ~/.kaggle/access_token.
    if os.environ.get("KAGGLE_API_TOKEN"):
        return True
    if (Path.home() / ".kaggle" / "access_token").exists():
        return True
    # Legacy kaggle CLI (1.x): username/key via kaggle.json or env vars.
    if os.environ.get("KAGGLE_USERNAME") and os.environ.get("KAGGLE_KEY"):
        return True
    kaggle_json = Path.home() / ".kaggle" / "kaggle.json"
    return kaggle_json.exists()


def _print_setup_instructions() -> None:
    print(
        """
No Kaggle API credentials found. This dataset requires a free Kaggle
account. To proceed:

  1. Create a Kaggle account (if you don't have one): https://www.kaggle.com
  2. Go to https://www.kaggle.com/settings/api -> "Create New Token" under
     "API". This shows a token string (not a downloadable file, on newer
     Kaggle CLI versions).
  3. Save it, either:

       mkdir -p ~/.kaggle
       echo "PASTE_TOKEN_HERE" > ~/.kaggle/access_token
       chmod 600 ~/.kaggle/access_token

     or export it for the current shell session:

       export KAGGLE_API_TOKEN=PASTE_TOKEN_HERE

     (Alternatively, run `kaggle auth login` for the interactive OAuth
     flow, which caches credentials for you.)
  4. Re-run: python data/download.py

No need to accept any competition rules for this step — the dataset used
here (thedrcat/daigt-v2-train-dataset) is a public Kaggle Dataset, not a
gated competition submission file.
""".strip()
    )


def main() -> int:
    if not _has_kaggle_credentials():
        _print_setup_instructions()
        return 1

    RAW_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Downloading {DATASET_SLUG} to {RAW_DIR} ...")
    result = subprocess.run(
        [
            "kaggle",
            "datasets",
            "download",
            "-d",
            DATASET_SLUG,
            "-p",
            str(RAW_DIR),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        print(
            "\nDownload failed. Common causes: invalid/expired API key, "
            "or network restrictions in this environment. See the error "
            "above for details.",
            file=sys.stderr,
        )
        return 1

    # kaggle CLI names the zip after the dataset slug's tail.
    zip_candidates = list(RAW_DIR.glob("*.zip"))
    if not zip_candidates:
        print("Download reported success but no .zip file was found.", file=sys.stderr)
        return 1

    for zip_path in zip_candidates:
        print(f"Extracting {zip_path.name} ...")
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(RAW_DIR)
        zip_path.unlink()

    csvs = sorted(p.name for p in RAW_DIR.glob("*.csv"))
    print(f"Done. Files in {RAW_DIR}: {csvs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
